---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: openfaas-cert
  namespace: openfaas
spec:
  commonName: functions.wiseapp.xyz
  secretName: openfaas-tls
  dnsNames:
    - functions.wiseapp.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: openfaas-gateway-ingress
  namespace: openfaas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`functions.wiseapp.xyz`)
      kind: Rule
      services:
        - name: gateway-external
          port: 8080
  tls:
    secretName: openfaas-tls
