apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: nodeinfo-api
  namespace: openfaas
spec:
  domain: api.wiseapp.xyz
  function: nodeinfo
  ingressType: traefik
  path: "/v1/nodeinfo(.*)"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-prod"
      # Change to ClusterIssuer if required
      # https://docs.cert-manager.io/en/latest/reference/clusterissuers.html
      # https://docs.cert-manager.io/en/latest/reference/issuers.html
      kind: "ClusterIssuer"
