---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: portainer-cert
  namespace: portainer
spec:
  commonName: portainer.wiseapp.xyz
  secretName: portainer-tls
  dnsNames:
    - portainer.wiseapp.xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
