apiVersion: v1
data:
  secretkey: UTFLSG40cEFBQjl1WTR5WU9Wa2FjSWd6aXNHQS9jRXVkRS9saG1GT0pkWitQZFl6YlBGWXV1NHBtZDBDVHdmUwptdzgrSkhCTnlITHdlVWk4NFEyYXN4VFNSc0NnYTZWN2JKYlFoT1BFM1ZBeERrVjB4SlVGWjRGUjMvSTA5ODJECk5HR1B6eXN4aWlyamNXZlJ5N1JxTW8vaC9scGpJU3hHcEJVelc1ZldNWUU9
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
