apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wiseapp-xyz
  namespace: default
  labels:
    "use-dns01-solver": "true"
spec:
  secretName: wiseapp-xyz-tls
  issuerRef:
    name: letsencrypt-dns-staging
    kind: ClusterIssuer
  dnsNames:
    - '*.wiseapp.xyz'
