apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    email: wisdomwolf@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-staging
    solvers:
      - selector:
          matchLabels:
            "use-dns01-solver": "true"
        dns01:
          cloudflare:
            email: wisdomwolf@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
